extends: './node_modules/eslint-config-airbnb/index.js'

rules:
    class-methods-use-this: 0
    no-warning-comments: 1
    comma-dangle:
      - 2
      - always-multiline

parser: babel-eslint


globals:
    document: true
