# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='static/uploads/%Y/%m/%d/'),
        ),
    ]
