# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='uploads.Document'),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='group.Group'),
        ),
    ]
